#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus     true
bspc config split_ratio           0.50 
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config border_width          2
bspc config window_gap            6
bspc config bottom_padding        34

bspc config focused_border_color "#88c0d0"
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#5e81ac"
bspc config presel_feedback_color "#88c0d0"

xsetroot -cursor_name left_ptr

bspc rule -a Wrapper-2.0 monitor=primary follow=on state=floating border=off rectangle=500x600+0+0
